# Generated by Django 4.0.6 on 2022-07-23 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summerhacker', '0002_board_member_delete_user_board_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
