# Generated by Django 4.0.6 on 2022-07-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_review_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='review',
            name='travel_place',
            field=models.CharField(default='', max_length=20),
        ),
    ]
