# Generated by Django 4.0.6 on 2022-07-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_review_title_alter_review_travel_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='review',
            name='travel_place',
            field=models.CharField(max_length=20),
        ),
    ]
